server:
  port: 8701
spring:
  application:
    name: feign-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
feign:
  hystrix:
    enabled: true #在 Feign 中开启 Hystrix

# Feign 结合 Ribbon 切换负载均衡策略算法
#user-service: # 表示作用到哪个微服务
#  ribbon:
#    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
#    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
#    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
#    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
#    # 我们也可以指定为其他策略，包括我们自己定义的，只要把相应的包路径写到这即可。
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    # ConnectTimeout: 500 #请求连接超时时间
#    # ReadTimeout: 1000 #请求处理的超时时间
#    # OkToRetryOnAllOperations: true #对所有请求都进行重试
#    # MaxAutoRetriesNextServer: 2 #切换实例的重试次数
#    # MaxAutoRetries: 1 #对当前实例的重试次数

# Ribbon 全局配置不生效？
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #修改负载均衡算法

logging:
  level:
    com.macro.cloud.service.UserService: debug